// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsP8noUZGZbKjl20wjHOO7cf3llNgtgEc',
    appId: '1:645220796780:web:ac9ccb6fd97243bad1cb49',
    messagingSenderId: '645220796780',
    projectId: 'codegram-223f3',
    authDomain: 'codegram-223f3.firebaseapp.com',
    storageBucket: 'codegram-223f3.appspot.com',
    measurementId: 'G-FGHFYM3PE0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1rastWtDkP7oUtU0sj20R35T6Sp9-ugw',
    appId: '1:645220796780:android:149e46e6bab0c9e9d1cb49',
    messagingSenderId: '645220796780',
    projectId: 'codegram-223f3',
    storageBucket: 'codegram-223f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6F5TG9yYsl6Wz85vRGugGwtXEyWckZA',
    appId: '1:645220796780:ios:a251147442c6eef7d1cb49',
    messagingSenderId: '645220796780',
    projectId: 'codegram-223f3',
    storageBucket: 'codegram-223f3.appspot.com',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ6F5TG9yYsl6Wz85vRGugGwtXEyWckZA',
    appId: '1:645220796780:ios:ed76dad5a0e58545d1cb49',
    messagingSenderId: '645220796780',
    projectId: 'codegram-223f3',
    storageBucket: 'codegram-223f3.appspot.com',
    iosBundleId: 'com.example.socialMediaApp.RunnerTests',
  );
}
